name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Homebrew Tap
        uses: actions/checkout@v4
        with:
          repository: fagom/homebrew-vault
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Update Homebrew Formula
        run: |
          SHA256=$(curl -L https://github.com/fagom/homebrew-vault/releases/latest/download/vault-mac | shasum -a 256 | awk '{print $1}')
          sed -i '' "s|sha256 \".*\"|sha256 \"${SHA256}\"|" Formula/vault.rb
          git add Formula/vault.rb
          git commit -m "Update Homebrew formula for new release"
          git push
